//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavratnaERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmpId { get; set; }
        public string FullName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string MobNo { get; set; }
        public string AlternetMobNo { get; set; }
        public string AdharDetail { get; set; }
        public string CompanyName { get; set; }
        public string Post { get; set; }
        public System.DateTime DateofJoining { get; set; }
        public System.DateTime DateofLeaving { get; set; }
        public string Photo { get; set; }
    }
}
